import { MilitaryBase } from "@/types";

function slugify(name: string): string {
  return name
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/\s+/g, "-")
    .replace(/[^\w\-]+/g, "")
    .replace(/\-\-+/g, "-")
    .replace(/^-+|-+$/g, "");
}

const MILITARY_BASES: MilitaryBase[] = [
  // France
  {
    id: slugify("Istres-Le Tubé"),
    name: "Istres-Le Tubé",
    country: "FR",
    operator: "FR",
    type: "air_base",
    lat: 43.52,
    lng: 4.92,
    status: "active",
    branch: "Armée de l'air",
    notes: null,
  },
  {
    id: slugify("Mont-de-Marsan"),
    name: "Mont-de-Marsan",
    country: "FR",
    operator: "FR",
    type: "air_base",
    lat: 43.91,
    lng: -0.5,
    status: "active",
    branch: "Armée de l'air",
    notes: null,
  },
  {
    id: slugify("Toulon"),
    name: "Toulon",
    country: "FR",
    operator: "FR",
    type: "naval_base",
    lat: 43.12,
    lng: 5.93,
    status: "active",
    branch: "Marine nationale",
    notes: null,
  },
  {
    id: slugify("Brest"),
    name: "Brest",
    country: "FR",
    operator: "FR",
    type: "naval_base",
    lat: 48.39,
    lng: -4.49,
    status: "active",
    branch: "Marine nationale",
    notes: null,
  },
  {
    id: slugify("Cherbourg"),
    name: "Cherbourg",
    country: "FR",
    operator: "FR",
    type: "naval_base",
    lat: 49.64,
    lng: -1.62,
    status: "active",
    branch: "Marine nationale",
    notes: null,
  },
  {
    id: slugify("Camp de Canjuers"),
    name: "Camp de Canjuers",
    country: "FR",
    operator: "FR",
    type: "army_base",
    lat: 43.62,
    lng: 6.45,
    status: "active",
    branch: "Armée de terre",
    notes: null,
  },
  {
    id: slugify("Mourmelon"),
    name: "Mourmelon",
    country: "FR",
    operator: "FR",
    type: "army_base",
    lat: 49.14,
    lng: 4.39,
    status: "active",
    branch: "Armée de terre",
    notes: null,
  },
  // USA
  {
    id: slugify("Ramstein"),
    name: "Ramstein",
    country: "DE",
    operator: "US",
    type: "air_base",
    lat: 49.44,
    lng: 7.6,
    status: "active",
    branch: "USAF",
    notes: null,
  },
  {
    id: slugify("Aviano"),
    name: "Aviano",
    country: "IT",
    operator: "US",
    type: "air_base",
    lat: 46.03,
    lng: 12.6,
    status: "active",
    branch: "USAF",
    notes: null,
  },
  {
    id: slugify("Rota"),
    name: "Rota",
    country: "ES",
    operator: "US",
    type: "naval_base",
    lat: 36.64,
    lng: -6.35,
    status: "active",
    branch: "US Navy",
    notes: null,
  },
  {
    id: slugify("Norfolk"),
    name: "Norfolk",
    country: "US",
    operator: "US",
    type: "naval_base",
    lat: 36.95,
    lng: -76.33,
    status: "active",
    branch: "US Navy",
    notes: null,
  },
  {
    id: slugify("Diego Garcia"),
    name: "Diego Garcia",
    country: "IO",
    operator: "US",
    type: "joint",
    lat: -7.32,
    lng: 72.41,
    status: "active",
    branch: null,
    notes: null,
  },
  {
    id: slugify("Camp Humphreys"),
    name: "Camp Humphreys",
    country: "KR",
    operator: "US",
    type: "army_base",
    lat: 36.96,
    lng: 127.03,
    status: "active",
    branch: "US Army",
    notes: null,
  },
  {
    id: slugify("Al Udeid"),
    name: "Al Udeid",
    country: "QA",
    operator: "US",
    type: "air_base",
    lat: 25.12,
    lng: 51.31,
    status: "active",
    branch: "USAF",
    notes: null,
  },
  {
    id: slugify("Incirlik"),
    name: "Incirlik",
    country: "TR",
    operator: "US",
    type: "air_base",
    lat: 37.0,
    lng: 35.43,
    status: "active",
    branch: "USAF",
    notes: null,
  },
  {
    id: slugify("Yokosuka"),
    name: "Yokosuka",
    country: "JP",
    operator: "US",
    type: "naval_base",
    lat: 35.28,
    lng: 139.67,
    status: "active",
    branch: "US Navy",
    notes: null,
  },
  {
    id: slugify("Guam"),
    name: "Guam",
    country: "GU",
    operator: "US",
    type: "air_base",
    lat: 13.58,
    lng: 144.93,
    status: "active",
    branch: "USAF",
    notes: "Anderson AFB",
  },
  {
    id: slugify("Pearl Harbor"),
    name: "Pearl Harbor",
    country: "US",
    operator: "US",
    type: "naval_base",
    lat: 21.35,
    lng: -157.97,
    status: "active",
    branch: "US Navy",
    notes: null,
  },
  {
    id: slugify("Fort Liberty"),
    name: "Fort Liberty",
    country: "US",
    operator: "US",
    type: "army_base",
    lat: 35.14,
    lng: -79.0,
    status: "active",
    branch: "US Army",
    notes: "ex-Fort Bragg",
  },
  {
    id: slugify("Abu Dhabi Al Dhafra"),
    name: "Abu Dhabi / Al Dhafra",
    country: "AE",
    operator: "US",
    type: "air_base",
    lat: 24.25,
    lng: 54.55,
    status: "active",
    branch: "USAF",
    notes: null,
  },
  {
    id: slugify("Bahrain"),
    name: "Bahrain",
    country: "BH",
    operator: "US",
    type: "naval_base",
    lat: 26.21,
    lng: 50.59,
    status: "active",
    branch: "US Navy",
    notes: "5th Fleet HQ",
  },
  // Russia
  {
    id: slugify("Kaliningrad"),
    name: "Kaliningrad",
    country: "RU",
    operator: "RU",
    type: "naval_base",
    lat: 54.71,
    lng: 20.51,
    status: "active",
    branch: "VMF",
    notes: null,
  },
  {
    id: slugify("Tartous"),
    name: "Tartous",
    country: "SY",
    operator: "RU",
    type: "naval_base",
    lat: 34.89,
    lng: 35.89,
    status: "active",
    branch: "VMF",
    notes: null,
  },
  {
    id: slugify("Khmeimim Latakia"),
    name: "Khmeimim/Latakia",
    country: "SY",
    operator: "RU",
    type: "air_base",
    lat: 35.41,
    lng: 35.95,
    status: "active",
    branch: "VKS",
    notes: null,
  },
  {
    id: slugify("Severomorsk"),
    name: "Severomorsk",
    country: "RU",
    operator: "RU",
    type: "naval_base",
    lat: 69.07,
    lng: 33.42,
    status: "active",
    branch: "VMF",
    notes: "Northern Fleet HQ",
  },
  {
    id: slugify("Engels-2"),
    name: "Engels-2",
    country: "RU",
    operator: "RU",
    type: "air_base",
    lat: 51.48,
    lng: 46.2,
    status: "active",
    branch: "VKS",
    notes: null,
  },
  {
    id: slugify("Vladivostok"),
    name: "Vladivostok",
    country: "RU",
    operator: "RU",
    type: "naval_base",
    lat: 43.11,
    lng: 131.9,
    status: "active",
    branch: "VMF",
    notes: "Pacific Fleet",
  },
  // China
  {
    id: slugify("Djibouti Support Base"),
    name: "Djibouti Support Base",
    country: "DJ",
    operator: "CN",
    type: "naval_base",
    lat: 11.55,
    lng: 43.15,
    status: "active",
    branch: "PLAN",
    notes: null,
  },
  {
    id: slugify("Hainan Yulin"),
    name: "Hainan/Yulin",
    country: "CN",
    operator: "CN",
    type: "naval_base",
    lat: 18.22,
    lng: 109.54,
    status: "active",
    branch: "PLAN",
    notes: null,
  },
  {
    id: slugify("Fiery Cross Reef"),
    name: "Fiery Cross Reef",
    country: "CN",
    operator: "CN",
    type: "joint",
    lat: 9.55,
    lng: 112.89,
    status: "active",
    branch: null,
    notes: "Sovereignty disputed",
  },
  // UK
  {
    id: slugify("Akrotiri"),
    name: "Akrotiri",
    country: "CY",
    operator: "UK",
    type: "air_base",
    lat: 34.59,
    lng: 32.99,
    status: "active",
    branch: "RAF",
    notes: null,
  },
  {
    id: slugify("HMNB Portsmouth"),
    name: "HMNB Portsmouth",
    country: "UK",
    operator: "UK",
    type: "naval_base",
    lat: 50.8,
    lng: -1.11,
    status: "active",
    branch: "RN",
    notes: null,
  },
  {
    id: slugify("HMNB Clyde"),
    name: "HMNB Clyde",
    country: "UK",
    operator: "UK",
    type: "naval_base",
    lat: 56.07,
    lng: -4.82,
    status: "active",
    branch: "RN",
    notes: "Submarine base",
  },
  // Djibouti (France)
  {
    id: slugify("Djibouti"),
    name: "Djibouti",
    country: "DJ",
    operator: "FR",
    type: "army_base",
    lat: 11.55,
    lng: 43.15,
    status: "active",
    branch: "Armée de terre",
    notes: "FFDj",
  },
  // Additions pour 50+
  {
    id: slugify("San Diego Naval Base"),
    name: "San Diego Naval Base",
    country: "US",
    operator: "US",
    type: "naval_base",
    lat: 32.68,
    lng: -117.12,
    status: "active",
    branch: "US Navy",
    notes: null,
  },
  {
    id: slugify("Bremerton"),
    name: "Bremerton",
    country: "US",
    operator: "US",
    type: "naval_base",
    lat: 47.56,
    lng: -122.66,
    status: "active",
    branch: "US Navy",
    notes: null,
  },
  {
    id: slugify("Spangdahlem"),
    name: "Spangdahlem",
    country: "DE",
    operator: "US",
    type: "air_base",
    lat: 49.98,
    lng: 6.69,
    status: "active",
    branch: "USAF",
    notes: null,
  },
  {
    id: slugify("Lakenheath"),
    name: "Lakenheath",
    country: "UK",
    operator: "US",
    type: "air_base",
    lat: 52.41,
    lng: 0.56,
    status: "active",
    branch: "USAF",
    notes: null,
  },
  {
    id: slugify("Mildenhall"),
    name: "Mildenhall",
    country: "UK",
    operator: "US",
    type: "air_base",
    lat: 52.36,
    lng: 0.48,
    status: "active",
    branch: "USAF",
    notes: null,
  },
  {
    id: slugify("Kadena"),
    name: "Kadena",
    country: "JP",
    operator: "US",
    type: "air_base",
    lat: 26.35,
    lng: 127.77,
    status: "active",
    branch: "USAF",
    notes: null,
  },
  {
    id: slugify("Kunsan"),
    name: "Kunsan",
    country: "KR",
    operator: "US",
    type: "air_base",
    lat: 35.9,
    lng: 126.62,
    status: "active",
    branch: "USAF",
    notes: null,
  },
  {
    id: slugify("Charles de Gaulle"),
    name: "Charles de Gaulle",
    country: "FR",
    operator: "FR",
    type: "air_base",
    lat: 49.01,
    lng: 2.55,
    status: "active",
    branch: "Armée de l'air",
    notes: null,
  },
  {
    id: slugify("Évreux"),
    name: "Évreux",
    country: "FR",
    operator: "FR",
    type: "air_base",
    lat: 49.03,
    lng: 1.22,
    status: "active",
    branch: "Armée de l'air",
    notes: null,
  },
  {
    id: slugify("Mururoa"),
    name: "Mururoa",
    country: "PF",
    operator: "FR",
    type: "joint",
    lat: -21.83,
    lng: -138.9,
    status: "closed",
    branch: null,
    notes: "Ex-nuclear test site",
  },
  {
    id: slugify("Gvardeyskoye"),
    name: "Gvardeyskoye",
    country: "RU",
    operator: "RU",
    type: "air_base",
    lat: 44.92,
    lng: 33.89,
    status: "active",
    branch: "VKS",
    notes: "Crimea",
  },
  {
    id: slugify("Murmansk"),
    name: "Murmansk",
    country: "RU",
    operator: "RU",
    type: "naval_base",
    lat: 69.0,
    lng: 33.07,
    status: "active",
    branch: "VMF",
    notes: null,
  },
  {
    id: slugify("Novorossiysk"),
    name: "Novorossiysk",
    country: "RU",
    operator: "RU",
    type: "naval_base",
    lat: 44.72,
    lng: 37.77,
    status: "active",
    branch: "VMF",
    notes: "Black Sea Fleet",
  },
  {
    id: slugify("Sevastopol"),
    name: "Sevastopol",
    country: "UA",
    operator: "RU",
    type: "naval_base",
    lat: 44.62,
    lng: 33.53,
    status: "active",
    branch: "VMF",
    notes: "Black Sea Fleet HQ (disputed)",
  },
  {
    id: slugify("Qingdao"),
    name: "Qingdao",
    country: "CN",
    operator: "CN",
    type: "naval_base",
    lat: 36.07,
    lng: 120.33,
    status: "active",
    branch: "PLAN",
    notes: "North Sea Fleet",
  },
  {
    id: slugify("Camp Lemonnier"),
    name: "Camp Lemonnier",
    country: "DJ",
    operator: "US",
    type: "joint",
    lat: 11.55,
    lng: 43.15,
    status: "active",
    branch: null,
    notes: "CJTF-HOA",
  },
];

export function getMilitaryBases(): MilitaryBase[] {
  return MILITARY_BASES;
}
