import { NuclearFacility } from "@/types";

const NUCLEAR_FACILITIES: NuclearFacility[] = [
  // France
  {
    id: "gravelines",
    name: "Gravelines",
    country: "FR",
    type: "power_plant",
    lat: 51.01,
    lng: 2.11,
    status: "operational",
    capacityMw: 5460,
    operator: "EDF",
    reactorCount: 6,
  },
  {
    id: "paluel",
    name: "Paluel",
    country: "FR",
    type: "power_plant",
    lat: 49.86,
    lng: 0.63,
    status: "operational",
    capacityMw: 5320,
    operator: "EDF",
    reactorCount: 4,
  },
  {
    id: "cattenom",
    name: "Cattenom",
    country: "FR",
    type: "power_plant",
    lat: 49.41,
    lng: 6.22,
    status: "operational",
    capacityMw: 5200,
    operator: "EDF",
    reactorCount: 4,
  },
  {
    id: "saint-alban",
    name: "Saint-Alban",
    country: "FR",
    type: "power_plant",
    lat: 45.41,
    lng: 4.75,
    status: "operational",
    capacityMw: 2670,
    operator: "EDF",
    reactorCount: 2,
  },
  {
    id: "bugey",
    name: "Bugey",
    country: "FR",
    type: "power_plant",
    lat: 45.8,
    lng: 5.27,
    status: "operational",
    capacityMw: 3580,
    operator: "EDF",
    reactorCount: 4,
  },
  {
    id: "tricastin",
    name: "Tricastin",
    country: "FR",
    type: "power_plant",
    lat: 44.33,
    lng: 4.73,
    status: "operational",
    capacityMw: 3660,
    operator: "EDF",
    reactorCount: 4,
  },
  {
    id: "flamanville",
    name: "Flamanville",
    country: "FR",
    type: "power_plant",
    lat: 49.54,
    lng: -1.88,
    status: "operational",
    capacityMw: 4310,
    operator: "EDF",
    reactorCount: 3,
  },
  {
    id: "la-hague",
    name: "La Hague",
    country: "FR",
    type: "reprocessing",
    lat: 49.68,
    lng: -1.88,
    status: "operational",
    capacityMw: null,
    operator: "Orano",
    reactorCount: null,
  },
  {
    id: "marcoule",
    name: "Marcoule",
    country: "FR",
    type: "research_reactor",
    lat: 44.14,
    lng: 4.71,
    status: "decommissioning",
    capacityMw: null,
    operator: "CEA",
    reactorCount: null,
  },
  {
    id: "cadarache",
    name: "Cadarache",
    country: "FR",
    type: "research_reactor",
    lat: 43.69,
    lng: 5.76,
    status: "operational",
    capacityMw: null,
    operator: "CEA",
    reactorCount: null,
  },
  {
    id: "chooz",
    name: "Chooz",
    country: "FR",
    type: "power_plant",
    lat: 50.09,
    lng: 4.79,
    status: "operational",
    capacityMw: 3000,
    operator: "EDF",
    reactorCount: 2,
  },
  {
    id: "civaux",
    name: "Civaux",
    country: "FR",
    type: "power_plant",
    lat: 46.46,
    lng: 0.66,
    status: "operational",
    capacityMw: 3000,
    operator: "EDF",
    reactorCount: 2,
  },
  {
    id: "blayais",
    name: "Blayais",
    country: "FR",
    type: "power_plant",
    lat: 45.26,
    lng: -0.69,
    status: "operational",
    capacityMw: 3640,
    operator: "EDF",
    reactorCount: 4,
  },
  {
    id: "cruas",
    name: "Cruas",
    country: "FR",
    type: "power_plant",
    lat: 44.63,
    lng: 4.76,
    status: "operational",
    capacityMw: 3660,
    operator: "EDF",
    reactorCount: 4,
  },
  {
    id: "dampierre",
    name: "Dampierre",
    country: "FR",
    type: "power_plant",
    lat: 47.55,
    lng: 2.52,
    status: "operational",
    capacityMw: 3560,
    operator: "EDF",
    reactorCount: 4,
  },
  {
    id: "belleville",
    name: "Belleville",
    country: "FR",
    type: "power_plant",
    lat: 47.51,
    lng: 2.88,
    status: "operational",
    capacityMw: 2620,
    operator: "EDF",
    reactorCount: 2,
  },
  {
    id: "nogent",
    name: "Nogent-sur-Seine",
    country: "FR",
    type: "power_plant",
    lat: 48.51,
    lng: 3.52,
    status: "operational",
    capacityMw: 2620,
    operator: "EDF",
    reactorCount: 2,
  },
  {
    id: "penly",
    name: "Penly",
    country: "FR",
    type: "power_plant",
    lat: 49.98,
    lng: 1.22,
    status: "operational",
    capacityMw: 2660,
    operator: "EDF",
    reactorCount: 2,
  },
  {
    id: "golfech",
    name: "Golfech",
    country: "FR",
    type: "power_plant",
    lat: 44.11,
    lng: 0.84,
    status: "operational",
    capacityMw: 2620,
    operator: "EDF",
    reactorCount: 2,
  },
  {
    id: "fessenheim",
    name: "Fessenheim",
    country: "FR",
    type: "power_plant",
    lat: 47.9,
    lng: 7.56,
    status: "shutdown",
    capacityMw: 1800,
    operator: "EDF",
    reactorCount: 2,
  },
  // UK
  {
    id: "hinkley-point-c",
    name: "Hinkley Point C",
    country: "UK",
    type: "power_plant",
    lat: 51.21,
    lng: -3.13,
    status: "under_construction",
    capacityMw: 3200,
    operator: "EDF Energy",
    reactorCount: 2,
  },
  {
    id: "sellafield",
    name: "Sellafield",
    country: "UK",
    type: "reprocessing",
    lat: 54.42,
    lng: -3.5,
    status: "operational",
    capacityMw: null,
    operator: "Sellafield Ltd",
    reactorCount: null,
  },
  {
    id: "sizewell",
    name: "Sizewell B",
    country: "UK",
    type: "power_plant",
    lat: 52.21,
    lng: 1.62,
    status: "operational",
    capacityMw: 1198,
    operator: "EDF Energy",
    reactorCount: 1,
  },
  {
    id: "heysham",
    name: "Heysham",
    country: "UK",
    type: "power_plant",
    lat: 54.03,
    lng: -2.93,
    status: "operational",
    capacityMw: 2400,
    operator: "EDF Energy",
    reactorCount: 4,
  },
  {
    id: "hunterston",
    name: "Hunterston B",
    country: "UK",
    type: "power_plant",
    lat: 55.72,
    lng: -4.89,
    status: "shutdown",
    capacityMw: 1200,
    operator: "EDF Energy",
    reactorCount: 2,
  },
  // Ukraine
  {
    id: "zaporizhzhia",
    name: "Zaporizhzhia",
    country: "UA",
    type: "power_plant",
    lat: 47.51,
    lng: 34.58,
    status: "operational",
    capacityMw: 5700,
    operator: "Energoatom",
    reactorCount: 6,
  },
  {
    id: "rivne",
    name: "Rivne",
    country: "UA",
    type: "power_plant",
    lat: 51.33,
    lng: 25.89,
    status: "operational",
    capacityMw: 2880,
    operator: "Energoatom",
    reactorCount: 4,
  },
  {
    id: "south-ukraine",
    name: "South Ukraine",
    country: "UA",
    type: "power_plant",
    lat: 47.82,
    lng: 31.21,
    status: "operational",
    capacityMw: 3000,
    operator: "Energoatom",
    reactorCount: 3,
  },
  {
    id: "khmelnytskyi",
    name: "Khmelnytskyi",
    country: "UA",
    type: "power_plant",
    lat: 50.30,
    lng: 26.65,
    status: "operational",
    capacityMw: 2000,
    operator: "Energoatom",
    reactorCount: 2,
  },
  // Russia
  {
    id: "kola",
    name: "Kola",
    country: "RU",
    type: "power_plant",
    lat: 67.46,
    lng: 32.47,
    status: "operational",
    capacityMw: 1760,
    operator: "Rosenergoatom",
    reactorCount: 4,
  },
  {
    id: "leningrad",
    name: "Leningrad",
    country: "RU",
    type: "power_plant",
    lat: 59.87,
    lng: 29.05,
    status: "operational",
    capacityMw: 4000,
    operator: "Rosenergoatom",
    reactorCount: 4,
  },
  {
    id: "kursk",
    name: "Kursk",
    country: "RU",
    type: "power_plant",
    lat: 51.68,
    lng: 35.61,
    status: "operational",
    capacityMw: 4000,
    operator: "Rosenergoatom",
    reactorCount: 4,
  },
  {
    id: "smolensk",
    name: "Smolensk",
    country: "RU",
    type: "power_plant",
    lat: 54.17,
    lng: 33.24,
    status: "operational",
    capacityMw: 3000,
    operator: "Rosenergoatom",
    reactorCount: 3,
  },
  {
    id: "kudankulam",
    name: "Kudankulam",
    country: "IN",
    type: "power_plant",
    lat: 8.17,
    lng: 77.71,
    status: "operational",
    capacityMw: 2000,
    operator: "NPCIL",
    reactorCount: 2,
  },
  // Iran
  {
    id: "bushehr",
    name: "Bushehr",
    country: "IR",
    type: "power_plant",
    lat: 28.83,
    lng: 51.35,
    status: "operational",
    capacityMw: 1000,
    operator: "AEOI",
    reactorCount: 1,
  },
  {
    id: "natanz",
    name: "Natanz",
    country: "IR",
    type: "enrichment",
    lat: 33.72,
    lng: 51.73,
    status: "operational",
    capacityMw: null,
    operator: "AEOI",
    reactorCount: null,
  },
  // Israel
  {
    id: "dimona",
    name: "Dimona",
    country: "IL",
    type: "military",
    lat: 31.0,
    lng: 35.15,
    status: "operational",
    capacityMw: null,
    operator: "IAEC",
    reactorCount: null,
  },
  // North Korea
  {
    id: "yongbyon",
    name: "Yongbyon",
    country: "KP",
    type: "military",
    lat: 39.8,
    lng: 125.76,
    status: "operational",
    capacityMw: null,
    operator: null,
    reactorCount: null,
  },
  // UAE
  {
    id: "barakah",
    name: "Barakah",
    country: "AE",
    type: "power_plant",
    lat: 23.96,
    lng: 52.26,
    status: "operational",
    capacityMw: 5600,
    operator: "ENEC",
    reactorCount: 4,
  },
  // China
  {
    id: "taishan",
    name: "Taishan",
    country: "CN",
    type: "power_plant",
    lat: 21.52,
    lng: 112.99,
    status: "operational",
    capacityMw: 3300,
    operator: "CGNPC",
    reactorCount: 2,
  },
  {
    id: "daya-bay",
    name: "Daya Bay",
    country: "CN",
    type: "power_plant",
    lat: 22.59,
    lng: 114.55,
    status: "operational",
    capacityMw: 1900,
    operator: "CGNPC",
    reactorCount: 2,
  },
  {
    id: "hongyanhe",
    name: "Hongyanhe",
    country: "CN",
    type: "power_plant",
    lat: 39.80,
    lng: 121.47,
    status: "operational",
    capacityMw: 4500,
    operator: "CGNPC",
    reactorCount: 6,
  },
  {
    id: "fukushima-daiichi",
    name: "Fukushima Daiichi",
    country: "JP",
    type: "power_plant",
    lat: 37.42,
    lng: 141.03,
    status: "decommissioning",
    capacityMw: null,
    operator: "TEPCO",
    reactorCount: 6,
  },
  // Japan
  {
    id: "rokkasho",
    name: "Rokkasho",
    country: "JP",
    type: "reprocessing",
    lat: 40.96,
    lng: 141.33,
    status: "operational",
    capacityMw: null,
    operator: "JNFL",
    reactorCount: null,
  },
  {
    id: "kashiwazaki-kariwa",
    name: "Kashiwazaki-Kariwa",
    country: "JP",
    type: "power_plant",
    lat: 37.42,
    lng: 138.60,
    status: "shutdown",
    capacityMw: 7965,
    operator: "TEPCO",
    reactorCount: 7,
  },
  {
    id: "sendai",
    name: "Sendai",
    country: "JP",
    type: "power_plant",
    lat: 31.84,
    lng: 130.19,
    status: "operational",
    capacityMw: 1780,
    operator: "Kyushu Electric",
    reactorCount: 2,
  },
  // USA
  {
    id: "palo-verde",
    name: "Palo Verde",
    country: "US",
    type: "power_plant",
    lat: 33.39,
    lng: -112.87,
    status: "operational",
    capacityMw: 3937,
    operator: "APS",
    reactorCount: 3,
  },
  {
    id: "vogtle",
    name: "Vogtle",
    country: "US",
    type: "power_plant",
    lat: 33.14,
    lng: -81.75,
    status: "operational",
    capacityMw: 2500,
    operator: "Southern Nuclear",
    reactorCount: 2,
  },
  {
    id: "surry",
    name: "Surry",
    country: "US",
    type: "power_plant",
    lat: 37.17,
    lng: -76.68,
    status: "operational",
    capacityMw: 1676,
    operator: "Dominion",
    reactorCount: 2,
  },
  {
    id: "three-mile-island",
    name: "Three Mile Island",
    country: "US",
    type: "power_plant",
    lat: 40.15,
    lng: -76.72,
    status: "shutdown",
    capacityMw: 819,
    operator: "Exelon",
    reactorCount: 1,
  },
  // Germany
  {
    id: "isar",
    name: "Isar 2",
    country: "DE",
    type: "power_plant",
    lat: 48.61,
    lng: 12.29,
    status: "operational",
    capacityMw: 1410,
    operator: "PreussenElektra",
    reactorCount: 1,
  },
  {
    id: "neckarwestheim",
    name: "Neckarwestheim",
    country: "DE",
    type: "power_plant",
    lat: 49.04,
    lng: 9.17,
    status: "operational",
    capacityMw: 1310,
    operator: "EnBW",
    reactorCount: 1,
  },
  // Belgium
  {
    id: "doel",
    name: "Doel",
    country: "BE",
    type: "power_plant",
    lat: 51.32,
    lng: 4.26,
    status: "operational",
    capacityMw: 2958,
    operator: "Engie",
    reactorCount: 4,
  },
  {
    id: "tihange",
    name: "Tihange",
    country: "BE",
    type: "power_plant",
    lat: 50.53,
    lng: 5.27,
    status: "operational",
    capacityMw: 3009,
    operator: "Engie",
    reactorCount: 3,
  },
  // Switzerland
  {
    id: "gosgen",
    name: "Gösgen",
    country: "CH",
    type: "power_plant",
    lat: 47.36,
    lng: 8.0,
    status: "operational",
    capacityMw: 1010,
    operator: "KKG",
    reactorCount: 1,
  },
  {
    id: "leibstadt",
    name: "Leibstadt",
    country: "CH",
    type: "power_plant",
    lat: 47.60,
    lng: 8.18,
    status: "operational",
    capacityMw: 1220,
    operator: "KKL",
    reactorCount: 1,
  },
  // Pakistan
  {
    id: "chashma",
    name: "Chashma",
    country: "PK",
    type: "power_plant",
    lat: 32.39,
    lng: 71.45,
    status: "operational",
    capacityMw: 1325,
    operator: "PAEC",
    reactorCount: 4,
  },
  // South Korea
  {
    id: "hanul",
    name: "Hanul",
    country: "KR",
    type: "power_plant",
    lat: 37.09,
    lng: 129.36,
    status: "operational",
    capacityMw: 5900,
    operator: "KHNP",
    reactorCount: 6,
  },
  {
    id: "kori",
    name: "Kori",
    country: "KR",
    type: "power_plant",
    lat: 35.33,
    lng: 129.30,
    status: "operational",
    capacityMw: 7300,
    operator: "KHNP",
    reactorCount: 7,
  },
];

export function getNuclearFacilities(): NuclearFacility[] {
  return NUCLEAR_FACILITIES;
}
